language: generic
sudo: required
services:
  -docker

before_install:
  - docker build -t raminblair/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true raminblair/client-test npm run test

after_success:
  - docker build -t raminblair/multi-client ./client
  - docker build -t raminblair/multi-server ./server
  - docker build -t raminblair/multi-nginx ./nginx
  - docker build -t raminblair/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push raminblair/multi-client
  - docker push raminblair/multi-server
  - docker push raminblair/multi-nginx
  - docker push raminblair/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-204737047155
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY